### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by Tf-arch** [cppcoffee/ipblock#1]
I am trying to install but it is giving error

![image](https://user-images.githubusercontent.com/83109300/152647878-3ab60391-6bea-45ac-b453-0c661f32b943.png)

I am using ubunto 20 iovisor installed  from https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---source

i have tried sudo apt install libbpf-dev but libbpf pakage not found.

it is giving error because of two headers that are endian.h and helper. h
what should I do??

**Comment by cppcoffee** [comment]
Hi, bpf_helpers.h need install libbpf. can use `apt install libbpf-dev` or install from source https://github.com/libbpf/libbpf

**Comment by cppcoffee** [comment]
hi @Tf-arch , already put libbpf in the repository.
